name: Run Vscode Integration tests
on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        
    - name: Get tests
      run: |
        git clone https://github.com/microsoft/vscode-test
        cd vscode-test
        npm install
        npm run compile
        
    - name: Run tests
      run: |
        xvfb-run --auto-servernum npm test
    #- name: Install
    #  uses: GabrielBB/xvfb-action@v1
    #  with:
    #    working-directory: vscode-test/sample
    #    run: |
    #      npm install
    #      xvfb-run -a npm test
    
    #  if: runner.os == 'Linux'
    #- run: |
    #    cd vscode-test/sample
    #    npm test
    #  if: runner.os != 'Linux' 
